### ISSUE TITLE
Feature request - Specific Font OCR

### ISSUE THREAD

**Issue by adam80** [antimatter15/ocrad.js#8]
THis is a great tool and I have been playing around with it for the last couple of days. Is there anyway to use a specific font for the basis of OCR, say Calibri? This means that if the user knows what the base font of the text/picture they are scanning then there would be a higher chance of conversion to the correct characters? That is what I am hoping for.

Please let me know of there is a way to do this if you can.

Thanks!

**Comment by bradisbell** [comment]
Is there any library you would suggest that can be configured for a particular font or be trained in some way?  I'm looking for a way to recognize scoreboard data, ideally in client-side JS, and am curious where to begin if not this library.  Thank you!

![scoreboard-guests](https://user-images.githubusercontent.com/1097509/49391241-bee40a80-f6f0-11e8-9099-05b29a4ae61e.png)
![scoreboard-10](https://user-images.githubusercontent.com/1097509/49391242-bee40a80-f6f0-11e8-91a4-a2880f18f468.png)
![scoreboard-68](https://user-images.githubusercontent.com/1097509/49391243-bee40a80-f6f0-11e8-8a43-b4916f335911.png)

**Comment by antimatter15** [comment]
Have you tried using tesseractJS instead? It should be generally more
accurate

**Comment by bradisbell** [comment]
@antimatter15 Thanks, yes I've tried it but it's mis-identifying the numbers since they do look quite a bit like other characters.  `8`, for example, appears often as a `B`.  If I could re-train the analysis, I think there'd be a lot more accurate detection.

I'm just getting started with this, so I'm not sure how to make my own dataset for Tesseract, but I'll continue looking into it.  Thank you for your advice!
